/**
 * Ren'Py Composer — gal AST → .rpy 脚本
 *
 * 目标格式: game/script.rpy + game/characters.rpy
 * 参考: https://www.renpy.org/doc/html/
 */

import { promises as fs } from 'node:fs'
import { join } from 'node:path'
import type { Composer, ExportContext, MultiFileOutput } from './composer.js'
import { mergeScriptAsts } from '../../shared/dsl/merge-scripts.js'
import {
  buildUniqueIdMap,
  collectJumpTargetIds,
  loadManifestCharacters,
  sanitizeExportId,
  toCharacterVar,
  type ManifestCharacter
} from './shared.js'
import type {
  AstNode,
  DialogueNode,
  SceneNode,
  ScriptNode
} from '../../shared/dsl/types.js'
import { walkScript } from '../../shared/dsl/visitor.js'
import { emitRenpyExpression } from './expression-to-renpy.js'

const INDENT = '    '

export interface RenpyAst {
  readonly scriptLines: readonly string[]
  readonly characters: readonly string[]
  readonly imageLines: readonly string[]
}

/** 将 gal 标识符转为 Ren'Py label 名(保留 CJK,替换标点) */
export const sanitizeRenpyLabel = (id: string): string => sanitizeExportId(id, 'n')

const escapeRenpyString = (s: string): string =>
  s.replace(/\\/g, '\\\\').replace(/"/g, '\\"')

const indentLine = (level: number, line: string): string => INDENT.repeat(level) + line

const resolveLabel = (id: string, labelMap: ReadonlyMap<string, string>): string =>
  labelMap.get(id) ?? sanitizeRenpyLabel(id)

/** 收集 scene/marker/choice/goto 目标,建立 gal id → Ren'Py label 映射 */
export const buildLabelMap = (scripts: readonly ScriptNode[]): Map<string, string> =>
  buildUniqueIdMap(collectJumpTargetIds(scripts), sanitizeRenpyLabel)

const collectCharacters = (scripts: readonly ScriptNode[]): string[] => {
  const names = new Set<string>()
  for (const script of scripts) {
    walkScript(script, {
      visitDialogue: (n: DialogueNode) => {
        if (n.character) names.add(n.character)
      }
    })
  }
  return Array.from(names).sort()
}


export const buildImageLines = (manifestChars: readonly ManifestCharacter[]): string[] => {
  const lines: string[] = ['# Generated by Galide — image definitions', '']
  let count = 0
  for (const char of manifestChars) {
    const charVar = toCharacterVar(char.name)
    for (const sprite of char.spriteSet ?? []) {
      if (!sprite.path) continue
      const state = sanitizeRenpyLabel(sprite.state || 'default')
      lines.push(`image ${charVar} ${state} = "${escapeRenpyString(sprite.path)}"`)
      count++
    }
  }
  if (count === 0) lines.push('# (no sprite images in .galproj)')
  lines.push('')
  return lines
}

const renpyPosition = (pos: DialogueNode['position']): string | undefined => {
  if (pos === 'left') return 'left'
  if (pos === 'right') return 'right'
  if (pos === 'center') return 'center'
  return undefined
}

const emitNodes = (
  nodes: readonly AstNode[],
  level: number,
  labelMap: ReadonlyMap<string, string>,
  lines: string[]
): void => {
  for (const node of nodes) {
    switch (node.type) {
      case 'dialogue': {
        if (node.sprite) {
          const charVar = toCharacterVar(node.character)
          const state = sanitizeRenpyLabel(node.sprite)
          const atPos = renpyPosition(node.position)
          const at = atPos ? ` at ${atPos}` : ''
          lines.push(indentLine(level, `show ${charVar} ${state}${at}`))
        }
        for (const text of node.lines) {
          lines.push(
            indentLine(
              level,
              `${toCharacterVar(node.character)} "${escapeRenpyString(text)}"`
            )
          )
        }
        break
      }
      case 'set': {
        const val = emitRenpyExpression(node.value)
        const op = node.op === 'set' ? '=' : node.op === 'add' ? '+=' : '-='
        lines.push(indentLine(level, `$ ${node.name} ${op} ${val}`))
        break
      }
      case 'if':
        for (const branch of node.branches) {
          if (branch.kind === 'if') {
            lines.push(
              indentLine(level, `if ${emitRenpyExpression(branch.condition!)}:`)
            )
          } else if (branch.kind === 'elif') {
            lines.push(
              indentLine(level, `elif ${emitRenpyExpression(branch.condition!)}:`)
            )
          } else {
            lines.push(indentLine(level, 'else:'))
          }
          emitNodes(branch.children, level + 1, labelMap, lines)
        }
        break
      case 'choice':
        lines.push(indentLine(level, 'menu:'))
        for (const opt of node.options) {
          const target = resolveLabel(opt.target, labelMap)
          const cond = opt.condition
            ? ` if ${emitRenpyExpression(opt.condition)}`
            : ''
          lines.push(
            indentLine(level + 1, `"${escapeRenpyString(opt.text)}"${cond}:`)
          )
          lines.push(indentLine(level + 2, `jump ${target}`))
        }
        break
      case 'goto':
        lines.push(indentLine(level, `jump ${resolveLabel(node.target, labelMap)}`))
        break
      case 'marker':
        lines.push(`label ${resolveLabel(node.id, labelMap)}:`)
        break
      case 'comment':
        lines.push(indentLine(level, `# ${node.text}`))
        break
      default:
        break
    }
  }
}

const emitScene = (
  scene: SceneNode,
  labelMap: ReadonlyMap<string, string>,
  lines: string[]
): void => {
  const label = resolveLabel(scene.id, labelMap)
  lines.push(`label ${label}:`)
  if (scene.background) {
    lines.push(
      indentLine(1, `scene expression "${escapeRenpyString(scene.background)}"`)
    )
  }
  if (scene.bgm) {
    lines.push(indentLine(1, `play music "${escapeRenpyString(scene.bgm)}"`))
  }
  emitNodes(scene.children, 1, labelMap, lines)
  lines.push('')
}

const buildScriptLines = (
  merged: ScriptNode,
  labelMap: ReadonlyMap<string, string>
): string[] => {
  const lines: string[] = [
    '# Generated by Galide — Ren\'Py export',
    '# Regenerate from .gal sources; do not edit by hand.',
    ''
  ]

  const scenes = merged.children.filter((n): n is SceneNode => n.type === 'scene')
  if (scenes.length > 0) {
    const firstLabel = resolveLabel(scenes[0]!.id, labelMap)
    lines.push('label start:')
    lines.push(indentLine(1, `jump ${firstLabel}`))
    lines.push('')
  }

  for (const scene of scenes) {
    emitScene(scene, labelMap, lines)
  }

  return lines
}

const buildCharactersRpy = (characters: readonly string[]): string => {
  if (characters.length === 0) return '# No characters\n'
  const lines = ['# Generated by Galide — character definitions', '']
  for (const name of characters) {
    const varName = toCharacterVar(name)
    lines.push(`define ${varName} = Character("${escapeRenpyString(name)}")`)
  }
  lines.push('')
  return lines.join('\n')
}

export class RenpyComposer implements Composer<RenpyAst, MultiFileOutput> {
  readonly name = 'renpy' as const
  readonly defaultFilename = 'game/script.rpy'

  async transform(ctx: ExportContext): Promise<RenpyAst> {
    const merged = mergeScriptAsts(ctx.asts)
    const scripts = ctx.asts.map((e) => e.ast)
    const labelMap = buildLabelMap(scripts.length > 0 ? scripts : [merged])
    const scriptLines = buildScriptLines(merged, labelMap)
    const characters = collectCharacters(scripts.length > 0 ? scripts : [merged])
    const manifestChars = await loadManifestCharacters(ctx.request.projectPath)
    const imageLines = buildImageLines(manifestChars)

    const assetsSrc = join(ctx.request.projectPath, 'assets')
    const assetsDest = join(ctx.outputDir, 'game', 'assets')
    try {
      await fs.mkdir(join(ctx.outputDir, 'game'), { recursive: true })
      await fs.cp(assetsSrc, assetsDest, { recursive: true })
    } catch (err) {
      console.warn(`[galide export] Ren'Py assets 复制失败: ${assetsSrc}`, err)
    }

    return { scriptLines, characters, imageLines }
  }

  emit(target: RenpyAst, _ctx: ExportContext): MultiFileOutput {
    return {
      kind: 'multi',
      files: [
        {
          path: 'game/script.rpy',
          content: [...target.scriptLines].join('\n')
        },
        {
          path: 'game/characters.rpy',
          content: buildCharactersRpy(target.characters)
        },
        {
          path: 'game/images.rpy',
          content: target.imageLines.join('\n')
        }
      ]
    }
  }
}
